"""Guided help: the tooltip texts of the interface, one or two plain sentences each, keyed by page and item.

Pages never read this dict directly: they call `ui.help("key")`, which returns the text in guided mode and None in
expert mode, so the same call site works in both. Texts are grounded in the README, the engine's docstrings
(`socialmas/sim.py`, `experiment.py`, `live.py`, `access.py`) and the glossaries shown in the app."""

HELP = {
    # ---- sidebar ----
    "sidebar.expert_mode": "Hides the explanatory tooltips (the small ⓘ icons) on every page. Switch it off again to get them back; the choice lasts for this browser session.",
    "sidebar.context": "The experiment the workspace pages (Configure, Replay, Live, History) work on. Open another one from the Experiments page.",

    # ---- experiments ----
    "experiments.page": "An experiment is a named configuration (population of agents, social graph, trust rules, run settings) together with the runs made on it. "
                        "It starts as an exact copy of one of the paper's pre-registered presets, which stay read-only.",
    "experiments.new": "Creates an experiment from one of the six paper presets and opens it in Configure.",
    "experiments.filter": "Shows only the experiments whose name, owner or origin preset contains this text.",
    "experiments.show_archived": "Archived experiments leave the list but keep their configuration and runs. Show them to restore one.",
    "experiments.card": "Badges: the paper preset the experiment derives from; the version of its saved configuration (it grows by one at every save); "
                        "archived; read-only for you (only the owner and administrators can change it); open in the workspace.",
    "experiments.card.facts": "Owner; number of agents; replay schedule as seeds × episodes per seed × policies; number of recorded runs; last update.",
    "experiments.card.last_replay": "Mean success rate of the main policies in the most recent replay run: the share of episodes whose task was solved.",
    "experiments.open": "Makes this the open experiment and goes to Configure.",
    "experiments.more": "Duplicate (a copy owned by you, without the runs), rename, archive or restore, according to your permissions.",
    "dialog.new.preset": "The pre-registered run of the paper to start from. The new experiment is an exact copy; Configure then shows every difference from it.",
    "dialog.new.name": "Any name up to 120 characters; it can be changed later with Rename.",
    "dialog.duplicate.name": "The copy keeps the configuration and the notes, becomes yours, and starts with an empty history of runs.",
    "dialog.rename.name": "Only the label changes: configuration, version and runs stay the same.",

    # ---- configure ----
    "configure.page": "Edits a draft kept in your session; nothing is stored until you press Save configuration. Runs always use the saved configuration.",
    "configure.strip": "The open experiment: owner, origin preset, configuration version, and whether your draft has unsaved changes.",
    "configure.origin": "Every parameter where the saved configuration differs from the paper preset it derives from. When there is none, a replay with the same "
                        "seeds reproduces the paper's per-seed numbers exactly, so any difference you see later is the effect of your edit.",
    "configure.origin.parameter": "Path of the parameter in the configuration (for example social.radius); 'agents' summarises the population.",
    "configure.origin.preset": "Value in the paper preset.",
    "configure.origin.this": "Value in this experiment's saved configuration.",
    "configure.population": "One row per agent: identifier, base model (whose measured outcomes are replayed), behavioural profile and the profile's parameters. "
                            "Add or delete rows to change the population; the graph degree is capped at the number of agents minus one.",
    "configure.population.id": "Unique identifier of the agent, shown in results and used by the best_fixed reference line.",
    "configure.population.base": "nano = gpt-4.1-nano, mini = gpt-4.1-mini. The agent's answers are replayed, domain by domain, from that model's measured outcomes.",
    "configure.population.profile": "How the agent behaves: honest, boaster, impostor, lazy, specialist, unstable or liar (see the profile glossary below).",
    "configure.population.lazy_p": "Lazy and unstable agents only: probability of returning an empty answer, which fails and still bills the call.",
    "configure.population.phase_length": "Unstable agents only: length in episodes of each phase; phases alternate honest and lazy.",
    "configure.population.domains": "Specialists only: the domains they declare and accept, comma-separated. Tasks outside them are refused at no cost.",
    "configure.tasks": "Which tasks the episodes draw and how an honest-type agent decides which domains to declare.",
    "configure.declaration_threshold": "An honest-type agent declares a domain when its base model's pass rate in that domain on the competence map is at least this value. "
                                       "Lower values mean more declarations.",
    "configure.task_pool": "all: the 350 measured tasks. discriminating: the 174 tasks passed by at least one base model, so that a failure reflects the agent and not an impossible task.",
    "configure.graph": "The initial social graph and the way it evolves during a run.",
    "configure.degree": "Initial number of contacts per agent: a random connected graph built from a spanning tree plus random edges up to this mean degree.",
    "configure.radius": "How far a requester looks for a worker: 1 = its direct contacts only; 2 = contacts of contacts as well, with the contact in between giving a referral opinion.",
    "configure.befriend": "After a successful episode the requester adds the worker to its contacts, so the graph grows with experience.",
    "configure.selection": "How a requester chooses a worker among the agents it can reach, from its own trust scores and the opinions of its contacts.",
    "configure.epsilon": "With this probability the requester explores: it picks a reachable agent at random instead of the best-scored one.",
    "configure.max_reselections": "When the chosen worker refuses (a specialist outside its domains), how many further candidates are tried before the episode fails.",
    "configure.declared_prior": "Score given to an agent with no trust record yet when it declares the task's domain.",
    "configure.undeclared_prior": "Score given to an agent with no trust record yet when it does not declare the task's domain.",
    "configure.referral_weight_default": "Weight of the opinion of a referrer the requester has no record about: 0 ignores it, 1 trusts it fully.",
    "configure.trust": "Each requester keeps a Beta reputation per worker: successes add to α, failures to β, and the trust score is their mean α / (α + β).",
    "configure.prior_alpha": "Initial pseudo-count of successes in the Beta prior. Larger priors make trust move more slowly.",
    "configure.prior_beta": "Initial pseudo-count of failures in the Beta prior.",
    "configure.domain_min_obs": "Minimum number of observations in a domain before the domain-specific trust replaces the overall one for that worker.",
    "configure.analysis": "Settings of the summaries, not of the simulation itself.",
    "configure.cold_start": "Length of the initial stretch of episodes reported separately as cold-start success, before trust had time to form.",
    "configure.best_fixed_agents": "Candidates for the best_fixed reference line, which always selects the first of them that is reachable. Needed only when best_fixed is among the policies.",
    "configure.run_settings": "The replay schedule. Seed i of your run uses the same random draws as seed i of the paper, so shared seeds are comparable one by one.",
    "configure.seeds": "Independent repetitions with different random draws; means and confidence intervals are computed over seeds. The paper uses 20.",
    "configure.episodes": "Episodes per seed and policy. Each episode is one task request, one selection and one outcome. Multiples of 100, the analysis window.",
    "configure.policies": "Selection policies to compare; each runs on every seed. best_fixed and oracle are reference lines that assume ground truth, not social policies.",
    "configure.bootstrap": "Resamples of the paired bootstrap that gives the 95% confidence intervals of the differences between policies. More resamples, smoother intervals, slower run.",
    "configure.notes": "Free text kept with the experiment: hypotheses, what changed and why. It is not part of the configuration, so saving notes does not create a version.",
    "configure.state": "Saving stores the draft as a new configuration version and makes it the one runs use. Discarding returns the draft to the saved configuration.",
    "configure.save": "Stores the draft as the next configuration version; disabled while the draft is invalid or identical to the saved configuration.",
    "configure.discard": "Throws away the edits of the draft and reloads the saved configuration.",
    "configure.download": "The draft as a JSON file, in the format the command line accepts (socialmas run --config).",
    "configure.upload": "Replaces the whole draft with the uploaded configuration; nothing is saved until you press Save configuration.",

    # ---- replay ----
    "replay.page": "Simulates the saved configuration over the outcomes measured once with real models: deterministic given the seed, no API call, no cost.",
    "replay.run": "Runs every selected policy on every seed and records the run on the experiment. An identical configuration already computed on this server is served from memory.",
    "replay.saved_config": "What a new run will use, with a time estimate calibrated on this server's speed.",
    "replay.picker": "The replay runs of this experiment, newest first: time, author, configuration version, schedule and mean success by policy. "
                     "The message next to it says whether the run was made with the current saved configuration or with an earlier version.",
    "replay.metric.social_vs_random": "Difference in mean success rate between the best social policy of the run and random selection, in percentage points: the paper's main effect (+8.6 in the main run).",
    "replay.metric.unreliable": "Share of selections that went to unreliable agents (lazy, impostor, unstable in a lazy phase) in the first 100-episode window and in the last window of the same unstable phase, for the best social policy. Learning shows as a decline.",
    "replay.metric.schedule": "Seeds × episodes per seed and policy, then the policies and agents of the run.",
    "replay.metric.elapsed": "Wall-clock time of the simulation on this server, and the size of the task pool it drew from.",
    "replay.metric.generated": "When the paper's run was produced, and the size of its task pool.",
    "replay.headline": "One row per policy, means over seeds. Success is the share of episodes whose task was solved.",
    "replay.headline.policy": "The selection policy (see the policy glossary in Configure). Reference lines assume ground truth.",
    "replay.headline.success": "Mean success rate over seeds: share of episodes whose task was solved.",
    "replay.headline.min": "Lowest per-seed success rate.",
    "replay.headline.max": "Highest per-seed success rate.",
    "replay.headline.cold": "Success rate in the first cold-start episodes of each seed, before trust had time to form.",
    "replay.headline.cost1000": "Replayed cost of the calls per 1,000 episodes, from the tokens measured for each task and model.",
    "replay.headline.cost_success": "Replayed cost per solved task.",
    "replay.headline.messages": "Messages per episode: request, referral questions and answers, refusals, new relationships.",
    "replay.headline.degree": "Mean number of contacts per agent at the end of the run.",
    "replay.headline.unreliable_first": "Share of selections that went to unreliable agents in the first 100-episode window.",
    "replay.headline.unreliable_last": "Same share in the last window that falls in the same phase of the unstable agents.",
    "replay.differences": "Each row is a pair of policies: the dot is the mean difference in success over seeds, in percentage points, the bar its 95% bootstrap confidence interval. "
                          "A bar that does not cross zero is a reliable effect; the dashed line marks the pre-registered minimal effect.",
    "replay.differences.comparison": "The two policies compared, first minus second.",
    "replay.differences.points": "Mean over seeds of the paired difference in success rate, in percentage points.",
    "replay.differences.ci_low": "Lower bound of the 95% bootstrap confidence interval.",
    "replay.differences.ci_high": "Upper bound of the 95% bootstrap confidence interval.",
    "replay.differences.seeds_positive": "Seeds where the first policy did better than the second, out of all seeds.",
    "replay.differences.cold": "The same difference restricted to the cold-start episodes.",
    "replay.success_windows": "Mean success rate in consecutive 100-episode windows. A rising curve means the policy learns whom to ask; flat lines are the references.",
    "replay.unreliable_windows": "Share of selections that go to unreliable agents in each 100-episode window; social policies push it down as trust forms.",
    "replay.messages_windows": "Messages per episode over time: referral questions and new relationships add messages, so this is the cost of discovery.",
    "replay.selection": "Who gets selected by each policy: the share of selections that went to each agent profile.",
    "replay.decline": "For each policy, the share of unreliable selections in the first window and in the last window of the same unstable phase, and the decline between them with its 95% interval.",
    "replay.decline.first": "Share of unreliable selections in the first 100-episode window.",
    "replay.decline.last": "Share in the last window that falls in the same phase of the unstable agents.",
    "replay.decline.points": "First minus last, in percentage points; positive means fewer unreliable selections at the end.",
    "replay.calibration": "Computed after the run, for evaluation only: how far the learned trust scores are from the true competences, and, with the referral check, the weight learned for honest versus lying referrers.",
    "replay.ground_truth": "The true pass rate of every agent per domain and its declarations, from the measured outcomes. Policies never see this table.",
    "replay.download.json": "The full results in the format of the paper's provenance files.",
    "replay.download.csv": "The headline table as CSV.",
    "replay.download.md": "Tables and notes as a Markdown report, the same the command line produces.",

    # ---- live ----
    "live.page": "Same population, graph, trust rules and policies as the replay, but honest-type executions are real OpenAI calls on the paper's 121 out-of-sample tasks, "
                 "graded before the trust update, under a spending cap that is never crossed.",
    "live.grader": "A separate service that runs the official BigCodeBench tests on each answer in an isolated container and returns pass or fail. Live runs are disabled while it is unreachable.",
    "live.dataset": "The 121 out-of-sample tasks are fetched once from Hugging Face (2.3 MB) and verified against the SHA-256 frozen by the paper.",
    "live.new_run": "Choose the schedule, read the quote, pick the key and the cap, then start. Lazy shirking, impostor and refused episodes make no call and cost nothing.",
    "live.episodes": "Episodes per seed and policy: each is one task request with, for honest-type workers, one real call.",
    "live.seeds": "Seeds of the paper's live validation to repeat; each adds a full pass over the policies.",
    "live.policies": "Policies that can run live: the reference lines that assume ground truth are excluded.",
    "live.quote": "Expected calls and cost from the paper's live run (calls per episode and mean cost per call), with a suggested cap at twice the expected cost.",
    "live.key_source": "Your own OpenAI key, kept in the server's memory for this run only, or the laboratory's shared key within the allowance an administrator gave you.",
    "live.key": "Sent only to OpenAI with store: false; never stored or logged. Ignored when the shared key is chosen.",
    "live.cap": "Upper bound on this run's spending. Before every call the ledger checks that the worst realistic cost of that call would not cross the cap; if it would, the run stops.",
    "live.start": "Fetches the dataset if needed, then runs episode by episode with a progress bar. The run is recorded on the experiment and, with the shared key, charged to your account.",
    "live.reference": "The paper's live validation of 27 September 2026: success and calls per policy over 600 episodes each, and the base models' transfer to unseen tasks.",
    "live.picker": "The live runs of this experiment, newest first: time, author, status, calls, upper cost, key used and mean success by policy.",
    "live.metric.status": "completed, or stopped by the cap or by an error (hover for the message).",
    "live.metric.calls": "Real API calls made: honest-type executions only, since lazy, impostor and refused episodes make none.",
    "live.metric.cost": "Upper cost: every input token at the uncached price plus the output tokens. The estimate with prompt caching is lower.",
    "live.policies_table": "Pooled over seeds: episodes, success rate, real calls, and the share of unreliable selections in the first and last 100-episode window.",
    "live.policies_table.calls": "Real API calls made by this policy.",
    "live.base_models": "Per base model: calls made live, the share of them that passed the grader, and the same model's pass rate on the competence map. Close values confirm the transfer to unseen tasks.",
    "live.base_models.map_rate": "Pass rate of the same model on the 350 tasks of the competence map used by the replay.",
    "live.success_windows": "Success rate of each policy in consecutive 100-episode windows of the live run.",
    "live.ledger": "One row per real call: who made it, which model and task, tokens in and out, upper cost, API status, latency, and the grader's verdict and time.",
    "live.ledger.upper_cost": "Cost of the call with every input token at the uncached price, as charged to the cap.",
    "live.ledger.grade": "Verdict of the grader on the answer: pass, fail, or an error of the grading itself.",
    "live.download.json": "The run without code and without the key: configuration, ledger, per-episode records.",
    "live.download.csv": "One row per episode with policy, seed, selected agent, effect and outcome.",

    # ---- history ----
    "history.page": "Every run recorded on the open experiment, replay and live, newest first, with the configuration version it used.",
    "history.metric.runs": "All runs of this experiment, replay and live.",
    "history.metric.replay": "Deterministic simulations over the measured outcomes; free.",
    "history.metric.live": "Runs with real OpenAI calls, and how many calls they made in total.",
    "history.metric.spending": "Sum of the upper costs of the live runs, own and shared keys together.",
    "history.table": "Newest first. Open a run below to see its results on the Replay or Live page.",
    "history.kind": "replay: simulation over measured outcomes; live: real calls.",
    "history.status": "completed, or how a live run stopped (cap reached, error).",
    "history.version": "The configuration version of the experiment when the run was made.",
    "history.current": "Ticked when the saved configuration is still the one this run was made with; unticked when it changed since.",
    "history.policies": "Mean success rate per policy in this run.",
    "history.calls": "Real API calls (live runs only).",
    "history.cost": "Upper cost in USD (live runs only).",
    "history.key": "own or shared: which OpenAI key the live run used.",
    "history.open_run": "Selects this run on its page (Replay or Live) and goes there.",

    # ---- paper comparison ----
    "paper.page": "The pre-registered results of the paper, byte for byte from its provenance files, and how the open experiment's selected replay run compares with them.",
    "paper.reference": "Which pre-registered run to show: the main run, its variants, or the v3 runs with thirty agents and lying referrers.",
    "paper.v3": "The v3 run with four lying referrers against its twin without liars, paired by seed: the damage liars do to each policy, and the defence the referral check gives.",
    "paper.v3.comparison": "Which two conditions or policies are compared, first minus second.",
    "paper.v3.points": "Mean paired difference in success over seeds, in percentage points.",
    "paper.compare": "Your selected replay run against this reference, policy by policy. With the same population and rules, the seeds both runs share must give identical numbers, "
                     "because the simulator is deterministic; with different settings, the deltas measure your change.",
    "paper.compare.run": "Mean success rate in your run.",
    "paper.compare.paper": "Mean success rate in the paper's run.",
    "paper.compare.delta": "Your run minus the paper, in percentage points.",
    "paper.compare.shared": "Seeds present in both runs (seed i is the same random draw in both).",
    "paper.compare.exact": "Ticked when the per-seed success rates coincide exactly on the shared seeds.",

    # ---- data and method ----
    "method.page": "Where the replay's numbers come from: a competence map measured once with real models, and the bundled reference files of the paper.",
    "method.map": "Tasks solved per domain by each of the three measured models, out of 50 drawn per domain. Replay agents inherit these outcomes through their base model.",
    "method.models": "Per model: tasks attempted, tasks passed, pass rate and the upper cost of measuring all 350 tasks.",
    "method.models.pass_rate": "Share of the 350 tasks whose answer passed the official tests.",
    "method.models.cost": "Upper cost of the 350 calls, every input token at the uncached price.",
    "method.provenance": "Licences, what the bundled data contain and what they deliberately leave out.",

    # ---- account ----
    "account.profile": "Your identifier, display name and role. Roles are fixed bundles of capabilities, assigned by a SysAdmin.",
    "account.capabilities": "Each badge is a capability your role grants. The app checks them before every action, not only when deciding what to show.",
    "account.password": "Changing your password signs out your other sessions. Passwords are stored as PBKDF2-SHA256 hashes.",

    # ---- administration ----
    "admin.page": "Accounts and roles, the shared OpenAI key with per-user allowances and a global cap, and the access log.",
    "admin.accounts": "One row per account. Temporary password means the person must still choose their own at the next sign-in; until then everything else is blocked for them.",
    "admin.accounts.role": "SysAdmin: everything, including accounts and settings. Researcher: replay, exports and live runs. Reviewer: replay and exports.",
    "admin.accounts.active": "Deactivated accounts cannot sign in and their sessions end at once. The last active administrator cannot be deactivated.",
    "admin.accounts.temporary": "Ticked while the person still has to replace the password an administrator set.",
    "admin.accounts.allowance": "USD this person may spend on the shared key (upper cost). 0 means they cannot use it.",
    "admin.accounts.spent": "Upper cost of the live runs this person charged to the shared key so far.",
    "admin.add": "No self sign-up and no email: you create the account with a temporary password and hand it over; the person must change it at the first sign-in.",
    "admin.add.id": "Immutable identifier used to sign in: lowercase letters, digits, dots, dashes, underscores, at most 64 characters.",
    "admin.add.name": "Display name shown in the interface and in the audit log.",
    "admin.add.role": "SysAdmin: everything. Researcher: replay, exports and live runs. Reviewer: replay and exports. Every account has exactly one role.",
    "admin.add.password": "At least 10 characters. Flagged as temporary: the person must choose their own at the first sign-in.",
    "admin.edit": "Change name, role, status, allowance, or set a new temporary password. Deactivation ends the person's sessions at once; prefer it to removal.",
    "admin.edit.active": "Unticked = deactivated: cannot sign in, sessions end. The change is refused if it would leave no active administrator.",
    "admin.edit.password": "Sets a new temporary password (the person must change it at the next sign-in) and ends their current sessions. Leave empty to keep the current one.",
    "admin.edit.allowance": "USD this person may spend on the shared key, as upper cost. 0 means they cannot use it. Every live run on the shared key is charged here.",
    "admin.roles": "The capabilities each role bundles, and what each capability allows.",
    "admin.shared_key": "One OpenAI key for the whole laboratory, encrypted on the data disk with a key derived from the session secret, never displayed again and never logged. "
                        "People use it on the Live page within their allowance; every run is charged to their account.",
    "admin.key_input": "Pasting a key replaces the current one; only its last four characters are kept in clear, for recognition.",
    "admin.remove_key": "Removes the shared key after confirmation. Allowances and the spending record are kept.",
    "admin.global_cap": "Ceiling on everyone's spending on the shared key together (upper cost). A person's remaining allowance is the smaller of their own allowance and what is left under this cap.",
    "admin.spending": "Spending on the shared key by user: runs, upper cost, calls and the last run.",
    "admin.log": "Every governance act and sign-in, newest first: account changes, password changes, allowances, shared-key use, live runs, experiments, sign-ins and failed sign-ins.",
    "admin.log.actor": "Who did it: an account id, or the bootstrap credential before the first account existed.",
    "admin.log.action": "What happened, as a dotted name: user.created, password.changed, session.login_failed, live.run, experiment.updated, ...",
}
